// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoCrjiGGTeZH0S-jY1OUiWzyjbaInBCqw',
    appId: '1:1024445569443:web:f26a627b9aadcd12f9a216',
    messagingSenderId: '1024445569443',
    projectId: 'proyecto-d383b',
    authDomain: 'proyecto-d383b.firebaseapp.com',
    storageBucket: 'proyecto-d383b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtO_8AUIj3zR3KanBvxtm_rNY2aiFemA',
    appId: '1:1024445569443:android:197687970a9c7c3af9a216',
    messagingSenderId: '1024445569443',
    projectId: 'proyecto-d383b',
    storageBucket: 'proyecto-d383b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw9DtJE50VXavU68YqtF_jtoq0iaGUOHk',
    appId: '1:1024445569443:ios:d4b0f4e7d79fa2eff9a216',
    messagingSenderId: '1024445569443',
    projectId: 'proyecto-d383b',
    storageBucket: 'proyecto-d383b.appspot.com',
    iosBundleId: 'com.example.desarrollat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw9DtJE50VXavU68YqtF_jtoq0iaGUOHk',
    appId: '1:1024445569443:ios:aea6b40ebf396320f9a216',
    messagingSenderId: '1024445569443',
    projectId: 'proyecto-d383b',
    storageBucket: 'proyecto-d383b.appspot.com',
    iosBundleId: 'com.example.desarrollat.RunnerTests',
  );
}
